log_level = "info"

[server]
host = "localhost"
port = 8080
verbose = false

[auth]
predifined_auth = { accounts = [
  { username = "admin", password = "secret" },
  { username = "user", password = "password" }
]}
